- app/views/layouts/application.html.erb
> [TEST] conflict test

- app/assets/stylesheets/application.scss
- app/views/admin/home/_header.html.erb
> [Finish]sawada-admin-header

- app/assets/stylesheets/application.scss
- app/views/users/_header.html.erb
> [Finish] nakajima-user-header

- app/views/home/top.html.erb
> only making visual

- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- ubuntu-bionic-18.04-cloudimg-console.log
> [Add] Userの新規ログインページを追加

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
> [Fix] User新規登録ページの修正

- app/assets/stylesheets/admin/home/top.scss
- app/controllers/admin/home_controller.rb
- app/views/admin/home/top.html.erb
> [Add] 管理者用トップページ作成終了

- app/assets/stylesheets/admins/sessions/new.scss
- app/controllers/application_controller.rb
- app/views/admins/confirmations/new.html.erb
- app/views/admins/mailer/confirmation_instructions.html.erb
- app/views/admins/mailer/email_changed.html.erb
- app/views/admins/mailer/password_change.html.erb
- app/views/admins/mailer/reset_password_instructions.html.erb
- app/views/admins/mailer/unlock_instructions.html.erb
- app/views/admins/passwords/edit.html.erb
- app/views/admins/passwords/new.html.erb
- app/views/admins/registrations/edit.html.erb
- app/views/admins/registrations/new.html.erb
- app/views/admins/sessions/new.html.erb
- app/views/admins/shared/_error_messages.html.erb
- app/views/admins/shared/_links.html.erb
- app/views/admins/unlocks/new.html.erb
> [Add]sawada-admin-login

- app/assets/stylesheets/users/confirm.scss
- app/views/users/confirm.html.erb
> 【yet】user-confirm

- app/controllers/users_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/users/edit.html.erb
> Mine user edit

- app/assets/stylesheets/devise/sessons/new.scss
- app/controllers/application_controller.rb
- app/views/devise/sessions/new.html.erb
byebugをapplication_controller.rbから削除
> [Fix]byebugをapplication_controller.rbから削除

- app/views/home/top.html.erb
> [Fix] ユーザートップ画面にヘッダー追加

- app/assets/stylesheets/users/confirm.scss
- app/views/admin/users/index.html.erb
- app/views/users/confirm.html.erb
> 【Finish】user-confirm and admin-user-index

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/users/show.scss
- app/controllers/admin/home_controller.rb
- app/controllers/users_controller.rb
- app/views/users/_header.html.erb
- app/views/users/show.html.erb
会員用マイページ作成
＆
会員用ヘッダー画面一部修正
admin/homeコントローラ内スペルミス修正
> [Add] 会員用マイページ作成

- app/assets/stylesheets/receivers/edit.scss
- app/assets/stylesheets/receivers/index.scss
- app/assets/stylesheets/users/show.scss
- app/controllers/receivers_controller.rb
- app/controllers/users_controller.rb
- app/views/receivers/edit.html.erb
- app/views/receivers/index.html.erb
ユーザー側　配達先登録/一覧ページ＆配達先編集ページ作成
＆
usersコントローラ内ストロングパラメータ記載場所修正
ユーザー showページ内タイトルの背景色変更
> [Add] ユーザー 配達先登録/一覧ページ＆配達先編集ページ作成

- app/controllers/users_controller.rb
- app/views/users/confirm.html.erb
> [Fix] 退会処理修正

- app/assets/stylesheets/admin/users/show.scss
- app/assets/stylesheets/devise/registration/new.scss
- app/assets/stylesheets/users/edit.scss
- app/controllers/admin/users_controller.rb
- app/views/admin/users/show.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/users/edit.html.erb
> Mine admin show

- app/assets/stylesheets/devise/registration/new.scss
- app/assets/stylesheets/users/edit.scss
- app/views/devise/registrations/new.html.erb
- app/views/users/edit.html.erb
> [Fix]User編集ページのstyleを修正

- app/assets/stylesheets/admin/users/edit.scss
- app/controllers/admin/users_controller.rb
- app/views/admin/users/edit.html.erb
> [Add]管理者　ユーザ編集画面

- app/assets/stylesheets/admin/products/index.scss
- app/views/admin/products/index.html.erb
> [Add] 管理者用商品一覧ページを追加

- app/assets/stylesheets/admins/genres/index.scss
- app/controllers/admin/genres_controller.rb
- app/views/admin/genres/index.html.erb
> Sawada admin genre index

- app/assets/stylesheets/products/show.scss
- app/controllers/cart_products_controller.rb
- app/controllers/products_controller.rb
- app/views/products/show.html.erb
> [Add] ユーザー商品詳細ページ作成

- app/controllers/admin/genres_controller.rb
> [Fix]管理者 ジャンル一覧・登録画面

- app/controllers/admin/users_controller.rb
- app/views/admin/users/index.html.erb
admin/user_controllerを修正
admin/user/index.html.erbの　ユーザー名前からshowへリンクを作成
> [Fix] 3/19 pull後のエラー、バグfix

- app/assets/stylesheets/admin/products/index.scss
- app/controllers/admin/products_controller.rb
- app/views/admin/products/index.html.erb
> [Fix] 管理者用商品一覧ページの修正

- app/assets/stylesheets/admin/products/new.scss
- app/views/admin/products/new.html.erb
> [Fix]管理者 商品登録画面修正

- app/assets/stylesheets/orders/confirm.scss
- app/assets/stylesheets/orders/thanks.scss
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/cart_products/index.html.erb
- app/views/orders/confirm.html.erb
- app/views/orders/thanks.html.erb
会員 注文確認画面＆注文完了画面作成
カート内商品一覧画面レイアウト調整
> [Add] 会員 注文確認画面＆注文完了画面作成

- app/controllers/orders_controller.rb
- app/models/order.rb
- app/models/order_product.rb
- app/views/orders/confirm.html.erb
- app/views/orders/new.html.erb
> [Add] 会員注文確認画面作成

- app/assets/stylesheets/orders/index.scss
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/orders/confirm.html.erb
- app/views/orders/index.html.erb
- app/views/products/show.html.erb
- config/application.rb
- config/locales/ja.yml
> [Add] 注文履歴一覧画面＆注文機能修正

- app/controllers/admin/products_controller.rb
- app/controllers/application_controller.rb
- app/views/admin/home/_header.html.erb
・管理者ページの商品新規登録後、商品一覧ページへ飛ぶように修正
・管理者ページのヘッダーにログアウト機能実装。ログアウト後はログイン画面へ
> 【Fix】管理者ページ商品新規登録画面、ログアウト機能

- app/views/cart_products/index.html.erb
- app/views/orders/confirm.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
> 【Fix】会員ページ商品画像

- app/controllers/products_controller.rb
- app/views/products/index.html.erb
> [Fix] 商品一覧ページの修正

- app/views/admin/orders/index.html.erb
> 【Fix】管理者ページ注文一覧画面

- app/controllers/products_controller.rb
- app/views/products/show.html.erb
・未ログイン時でも商品閲覧可能に変更
・ログインしていなければカートに商品追加ができないよう変更
> 【Fix】未ログイン時での閲覧制限に関して

- app/controllers/users_controller.rb
- app/views/home/top.html.erb
・退会ボタンでステータスがfalseに変更されると同時にログアウトもされるよう変更
> [Fix] ユーザー退会機能修正

- app/controllers/admin/genres_controller.rb
- app/controllers/admin/home_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/admin/products_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/cart_products_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/receivers_controller.rb
- app/controllers/users_controller.rb
・ログインしていないユーザーに見られたくないページにauthenticate機能を追加
> 【Add】各controllerにauthenticateを追加

- app/views/admin/users/index.html.erb
> 【Fix】管理ページ会員一覧修正

- app/controllers/admin/orders_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/products_controller.rb
- app/views/admin/orders/index.html.erb
- app/views/admin/products/index.html.erb
- app/views/admin/users/index.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/users/edit.html.erb
・管理ページ：user,order,productのページネーション修正
・会員ページ：新規登録画面と会員情報編集画面のオートフォーカス位置を修正
> 【Fix】管理ページ画面ページネーション設定＆オートフォーカス修正

- config/locales/devise.ja.yml
・translation missingのアラートが英語になっていたので、
configにdevise.ja.ymlファイルを追加し日本語を追加した。
> 【Add】devise日本語化

- app/controllers/admin/orders_controller.rb
- app/views/admin/home/_header.html.erb
- app/views/admin/home/top.html.erb
- app/views/admin/users/show.html.erb
・adminトップから当日の注文一覧、会員詳細から会員一覧、ヘッダーから会員一覧を見られるように修正
> 【Fix】管理ページリンク先の修正

- app/controllers/admin/genres_controller.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
・管理者ページのジャンルindexとeditのエラー表示を追加
> 【Add】ジャンルindex,editのエラー追加

- app/assets/javascripts/admin/genres.coffee
- app/assets/stylesheets/admin/home/_footer.scss
- app/views/cart_products/index.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/home/top.html.erb
- app/views/orders/confirm.html.erb
- app/views/orders/index.html.erb
- app/views/orders/new.html.erb
- app/views/orders/show.html.erb
- app/views/orders/thanks.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- app/views/receivers/edit.html.erb
- app/views/receivers/index.html.erb
- app/views/users/_footer.html.erb
- app/views/users/confirm.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
> [Add] Userページにフッターを追加

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/home.scss
- app/assets/stylesheets/products/show.scss
- app/assets/stylesheets/products/user-products-index.scss
- app/assets/stylesheets/users/_header.scss
- app/views/home/top.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- app/views/users/_header.html.erb
> Mine style sidebar fix

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/users/_header.scss
- app/views/users/_header.html.erb
> [Fix] bodyとheaderの背景を変更

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/home.scss
- app/assets/stylesheets/users/_header.scss
- app/views/home/top.html.erb
- app/views/users/_header.html.erb
> Mine style top fix 2

- app/views/home/about.html.erb
- app/views/users/_footer.html.erb
> 【Add】aboutページ作成

- app/assets/stylesheets/admin/products/index.scss
- app/assets/stylesheets/home.scss
- app/assets/stylesheets/products/show.scss
- app/assets/stylesheets/products/user-products-index.scss
- app/views/admin/users/index.html.erb
- app/views/cart_products/index.html.erb
- app/views/orders/show.html.erb
- app/views/products/show.html.erb
- app/views/users/edit.html.erb
・ユーザー　注文履歴詳細画面のタイトル修正
・各ページ　タイトルのfont-weightやh3に統一されてないページ修正
・ユーザー側商品showの表示画像サイズが、設定画像によって変化しないよう修正
> [Fix] レイアウト調整

- app/assets/stylesheets/admin/home/_footer.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/home.scss
- app/views/cart_products/index.html.erb
- app/views/home/top.html.erb
- app/views/orders/confirm.html.erb
- app/views/products/index.html.erb
- app/views/users/_footer.html.erb
[Fix]
・Userのfooterを修正
・Userの注文確認ページと注文ページのtable背景を修正
・UserのTopページのstyleを修正
> [Fix] UserのStyleを修正
